### ISSUE TITLE
 undefined symbol: _ZN17fastertransformer13cublasAlgoMapC1ESsSs

### ISSUE THREAD

**Issue by NJU-yasuo** [NVIDIA/FasterTransformer#220]
hello, i try to build ft on A100 , the build succeed but  error occurred running python bert_example.py
 

![image](https://user-images.githubusercontent.com/50507540/167683985-0a01aaae-845d-43a4-9b19-682ebe06e4af.png)

cuda  11.1
cudnn   8.0.5
pytorch  1.8.0

**Comment by byshiue** [comment]
This is a link error.
What branch and docker do you use? Do you modify any code?

**Comment by NJU-yasuo** [comment]
the latest branch
result of nvidia-smi : 
<img width="688" alt="截屏2022-05-11 上午10 57 56" src="https://user-images.githubusercontent.com/50507540/167759939-932868d4-ecda-41f6-aeae-7c7bee1a33f8.png">

and as in docker, 
<img width="433" alt="截屏2022-05-11 上午10 58 59" src="https://user-images.githubusercontent.com/50507540/167760067-2d7d9c6e-d4a3-4d52-b9c9-e21cd936aa82.png">

i didn't modify and code

**Comment by byshiue** [comment]
What docker do you use?

**Comment by NJU-yasuo** [comment]
docker on the company cloud， not sure

**Comment by byshiue** [comment]
Can you try the docker we suggest in the document.

**Comment by NJU-yasuo** [comment]
ok，tks

**Comment by maningning** [comment]
I encountered the same problem as you, also on the A100 platform, and also used the company's docker. After switching to docker as suggested by the documentation, this situation disappeared. But I really hope NV can solve this problem.

**Comment by byshiue** [comment]
Hi, @maningning , @NJU-yasuo , this problem is solved in https://github.com/NVIDIA/FasterTransformer/commit/920f635bdab2e9ea56cd2da1c452f65fda8cbe8c. The reason is the CXX ABI issue.

**Comment by Missmiaom** [comment]
Unfortunately, I still encounter this problem, but it is a troublesome thing for me to replace the official image, is there any solution?

fasttransform version: release/v5.3_tag
python: 3.8.16
gcc: 7.5.0
Ubuntu 18.04.5

**Comment by Missmiaom** [comment]
The error disappeared after modifying the following code

```
--- a/src/fastertransformer/kernels/longformer_kernels.cu
+++ b/src/fastertransformer/kernels/longformer_kernels.cu
@@ -76,6 +76,15 @@ size_t getInitLongformerCubStorage(const int seq_len)
     return tmp_storage_bytes;
 }
 
+template size_t
+getInitLongformerCubStorage<float>(const int seq_len);
+template size_t
+getInitLongformerCubStorage<half>(const int seq_len);
+#ifdef ENABLE_BF16
+template size_t
+getInitLongformerCubStorage<__nv_bfloat16>(const int seq_len);
+#endif
+
 template<typename T>
 __global__ void localAttnMaskShiftKernel(T* local_attn_mask, T* out, int thread_block_repeat, int total_len)
 {
```

**Comment by cody-moveworks** [comment]
Hi, I ran into a similar issue and the applying the changes suggested by @Missmiaom was what fixed my issue. 

For reference, here is my environment:

FasterTransformer version: pinned to commit `1cf9b515f3aa35d5483b1fd00aecc03fc9347dad`.
Python version: 3.8.13
gcc version: 7.5.0
Ubuntu version: 20.04 

@byshiue Can you evaluate if this change should be merged into the main branch?

**Comment by MrWaterZhou** [comment]
same problem
compiling with gcc >= 9(devtoolset-9) solves the problem
